# -*- coding: utf-8 -*-
"""Gilang Ferdiansyah - Proyek Analysis Data.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-jvsb2F72LyogNwByTU43jwi-BirepJe

# Proyek Analisis Data: [Bike Sharing Dataset]
- **Nama:** Gilang Ferdiansyah
- **Email:** m009d4ky2095@bangkit.academy
- **ID Dicoding:** pohoncemara2

## Menentukan Pertanyaan Bisnis

- Bagaimana pola sewa sepeda harian berdasarkan waktu, seperti perubahan jumlah sewa dalam satu bulan atau per jam?
- Apakah terdapat perbedaan pola sewa sepeda harian antara hari kerja dan hari libur?

## Import Semua Packages/Library yang Digunakan
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import streamlit as st
st.set_option('deprecation.showPyplotGlobalUse', False)

# Judul Dashboard
st.title("Bike Sharing Dashboard")
st.sidebar.markdown("Gilang Ferdiansyah")
st.sidebar.markdown("Ig : glngf_")
st.sidebar.markdown("Email: gilangf150203@gmail.com")


day = pd.read_csv('https://raw.githubusercontent.com/glngf/Data-Analaysis-BIKE-SHARING/ea39d4b47bfb7f03a3c5427615e5bc5b8c5f4601/day.csv')

hour = pd.read_csv('https://raw.githubusercontent.com/glngf/Data-Analaysis-BIKE-SHARING/ea39d4b47bfb7f03a3c5427615e5bc5b8c5f4601/hour.csv')

print("Jumlah baris di DataFrame day:", day.shape[0])
print("Jumlah baris di DataFrame hour:", hour.shape[0])

bike_share = day.merge(hour, on='dteday', how='inner', suffixes=('_daily', '_hourly'))


day.rename(columns={'yr': 'year', 'mnth': 'month', 'dteday': 'Date'}, inplace=True)

day['Date'] = pd.to_datetime(day['Date'])

day.info()

hour.rename(columns={'yr': 'year', 'mnth': 'month', 'dteday': 'Date', 'hr' : 'hour'}, inplace=True)

hour['Date'] = pd.to_datetime(hour['Date'])

hour.info()

#1
plt.figure(figsize=(10, 8))
sns.barplot(x="mnth_daily", y="cnt_daily", data=bike_share)
plt.title("Pola sewa sepeda harian berdasarkan bulan")
plt.xlabel("Bulan")
plt.ylabel("Jumlah Sewa Sepeda Harian")
plt.show()
st.pyplot()

#2
# Visualisasi dengan seaborn
plt.figure(figsize=(10, 8))
sns.barplot(x="workingday_daily", y="cnt_daily", data=bike_share)
# Menambahkan keterangan "weekend" dan "weekdays"
plt.title("Pola Sewa Sepeda Harian antara Hari Kerja dan Hari Libur")
plt.xlabel("Hari Kerja ( Weekdays,  Weekend)")
plt.ylabel("Jumlah Sewa Sepeda Harian")
plt.xticks([0, 1], ["Weekend", "Weekdays"])  # Menambahkan label pada sumbu x
st.pyplot()